// Generated by CoffeeScript 1.4.0
(function() {

  ($(document)).ready(function() {
    var socket;
    socket = io.connect('https://127.0.0.1:8088');
    return socket.on('ping', function() {
      return socket.emit('pong');
    });
  });

}).call(this);
